### ISSUE TITLE
running tests fails

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Distraction-Shield#122]
Hi Jeroen,

How are you? 

With @ancasuliman we are reviving the Distraction Shield project, and 
all seems to be well, but the tests are failing as you can see also in 
Travis: 

https://travis-ci.org/zeeguu-ecosystem/Distraction-Shield/jobs/461792999#L591

Do you have any idea of why this is? 
What is that line doing? 
Can we do it in a different way? 
My suspicion is that this is due to the latest version of some library not being able to interpret the code...

**Comment by dunnkers** [comment]
Hi @mircealungu ! I have a bit of time now so I can take a look at what's going on. Cool that you guys are reviving Distraction Shield.

**Comment by dunnkers** [comment]
The problem seems to only occur in Travis. Locally still running fine. As the problem occurred not from edits but just over time, it probably has to do with a dependency acting differently in a different version.

Edit: 
→ After pinning down all dependencies the build works again.
<img width="470" alt="bildschirmfoto 2018-12-05 um 15 03 36" src="https://user-images.githubusercontent.com/744430/49518507-16c07400-f89f-11e8-9b42-21f750309064.png">
[
https://travis-ci.org/zeeguu-ecosystem/Distraction-Shield/builds/463856922?utm_source=github_status&utm_medium=notification](https://travis-ci.org/zeeguu-ecosystem/Distraction-Shield/builds/463856922?utm_source=github_status&utm_medium=notification)

So, one of the dependencies is causing the problem. I suspect one of broccoli's.

**Comment by mircealungu** [comment]
so it was the dependencies... aiii iaaa. and at the speed with which node packages change this is not surprising... 

anyway, if you send a PR to the master we'll stay with these as much as possible!

**Comment by dunnkers** [comment]
Tried a couple packages but couldn't find the exact one. Create a PR to master. Cheers 🍻

**Comment by mircealungu** [comment]
Eheh. I also tried a couple of broccolis the other day, but gave up :)
Do you still work with JS these days?
In any case, I'm impressed with the fast reaction time :)
