### ISSUE TITLE
Update the default value of the interval between intercepts to 10 min

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Distraction-Shield#125]
the default value of 1min (as in the screenshot) is quite annoying if the user does not change it:

![screen shot 2018-12-05 at 4 41 11 pm](https://user-images.githubusercontent.com/464519/49524777-b0dae900-f8ac-11e8-9aed-316650212f03.png)

**Comment by dunnkers** [comment]
Issue became irrelevant due to [Revival](https://github.com/zeeguu-ecosystem/Distraction-Shield/milestone/1).

A new form of UI/UX is used to set time intervals.

![Screenshot_2019-07-09_09-47-11](https://user-images.githubusercontent.com/744430/60869189-c9d6be80-a22e-11e9-9ee2-836f44e0246c.png)

Default time is 5 min, but can be changed anytime and is saved.
